# Generated by Django 5.1.2 on 2025-01-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_favorite_customuser_introduction_and_more'),
        ('blogs', '0011_delete_category_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='blogs.blog', verbose_name='お気に入りのblog'),
        ),
    ]
