# Generated by Django 5.1.2 on 2025-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='media/unknown.jpg', null=True, upload_to=''),
        ),
    ]
