# Generated by Django 5.1.2 on 2024-12-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_comment_blog_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reply',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
