# Generated by Django 5.1.2 on 2024-12-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_likeforblog_user_likeforcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeforcomment',
            name='likefor',
        ),
        migrations.RemoveField(
            model_name='likeforcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeForBlog',
        ),
        migrations.DeleteModel(
            name='LikeForComment',
        ),
    ]
